// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package axi_llc_status_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 9;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_0_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_1_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_2_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_3_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_4_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_5_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_6_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_7_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_8_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_9_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_10_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_11_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_12_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_13_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_14_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_15_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_16_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_17_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_18_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_19_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_20_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_21_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_22_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_23_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_24_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_25_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_26_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_27_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_28_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_29_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_30_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_31_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_32_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_33_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_34_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_35_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_36_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_37_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_38_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_39_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_40_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_41_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_42_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_43_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_44_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_45_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_46_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_47_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_48_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_49_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_50_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_51_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_52_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_53_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_54_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_55_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_56_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_57_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_58_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_59_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_60_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_61_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_62_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_63_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_64_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_65_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_66_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_67_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_68_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_69_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_70_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_71_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_72_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_73_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_74_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_75_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_76_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_77_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_78_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_79_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_80_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_81_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_82_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_83_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_84_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_85_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_86_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_87_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_88_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_89_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_90_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_91_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_92_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_93_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_94_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_95_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_96_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_97_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_98_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_99_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_100_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_101_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_102_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_103_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_104_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_105_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_106_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_107_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_108_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_109_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_110_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_111_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_112_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_113_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_114_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_115_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_116_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_117_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_118_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_119_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_120_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_121_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_122_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_123_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_124_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_125_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_126_reg_t;

  typedef struct packed {
    logic [3:0]  q;
    logic        qe;
    logic        re;
  } axi_llc_status_reg2hw_status_127_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_0_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_1_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_2_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_3_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_4_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_5_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_6_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_7_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_8_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_9_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_10_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_11_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_12_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_13_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_14_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_15_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_16_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_17_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_18_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_19_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_20_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_21_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_22_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_23_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_24_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_25_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_26_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_27_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_28_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_29_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_30_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_31_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_32_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_33_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_34_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_35_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_36_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_37_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_38_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_39_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_40_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_41_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_42_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_43_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_44_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_45_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_46_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_47_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_48_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_49_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_50_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_51_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_52_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_53_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_54_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_55_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_56_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_57_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_58_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_59_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_60_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_61_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_62_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_63_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_64_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_65_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_66_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_67_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_68_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_69_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_70_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_71_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_72_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_73_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_74_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_75_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_76_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_77_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_78_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_79_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_80_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_81_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_82_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_83_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_84_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_85_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_86_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_87_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_88_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_89_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_90_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_91_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_92_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_93_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_94_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_95_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_96_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_97_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_98_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_99_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_100_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_101_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_102_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_103_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_104_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_105_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_106_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_107_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_108_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_109_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_110_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_111_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_112_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_113_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_114_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_115_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_116_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_117_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_118_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_119_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_120_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_121_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_122_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_123_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_124_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_125_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_126_reg_t;

  typedef struct packed {
    logic [3:0]  d;
  } axi_llc_status_hw2reg_status_127_reg_t;

  // Register -> HW type
  typedef struct packed {
    axi_llc_status_reg2hw_status_0_reg_t status_0; // [767:762]
    axi_llc_status_reg2hw_status_1_reg_t status_1; // [761:756]
    axi_llc_status_reg2hw_status_2_reg_t status_2; // [755:750]
    axi_llc_status_reg2hw_status_3_reg_t status_3; // [749:744]
    axi_llc_status_reg2hw_status_4_reg_t status_4; // [743:738]
    axi_llc_status_reg2hw_status_5_reg_t status_5; // [737:732]
    axi_llc_status_reg2hw_status_6_reg_t status_6; // [731:726]
    axi_llc_status_reg2hw_status_7_reg_t status_7; // [725:720]
    axi_llc_status_reg2hw_status_8_reg_t status_8; // [719:714]
    axi_llc_status_reg2hw_status_9_reg_t status_9; // [713:708]
    axi_llc_status_reg2hw_status_10_reg_t status_10; // [707:702]
    axi_llc_status_reg2hw_status_11_reg_t status_11; // [701:696]
    axi_llc_status_reg2hw_status_12_reg_t status_12; // [695:690]
    axi_llc_status_reg2hw_status_13_reg_t status_13; // [689:684]
    axi_llc_status_reg2hw_status_14_reg_t status_14; // [683:678]
    axi_llc_status_reg2hw_status_15_reg_t status_15; // [677:672]
    axi_llc_status_reg2hw_status_16_reg_t status_16; // [671:666]
    axi_llc_status_reg2hw_status_17_reg_t status_17; // [665:660]
    axi_llc_status_reg2hw_status_18_reg_t status_18; // [659:654]
    axi_llc_status_reg2hw_status_19_reg_t status_19; // [653:648]
    axi_llc_status_reg2hw_status_20_reg_t status_20; // [647:642]
    axi_llc_status_reg2hw_status_21_reg_t status_21; // [641:636]
    axi_llc_status_reg2hw_status_22_reg_t status_22; // [635:630]
    axi_llc_status_reg2hw_status_23_reg_t status_23; // [629:624]
    axi_llc_status_reg2hw_status_24_reg_t status_24; // [623:618]
    axi_llc_status_reg2hw_status_25_reg_t status_25; // [617:612]
    axi_llc_status_reg2hw_status_26_reg_t status_26; // [611:606]
    axi_llc_status_reg2hw_status_27_reg_t status_27; // [605:600]
    axi_llc_status_reg2hw_status_28_reg_t status_28; // [599:594]
    axi_llc_status_reg2hw_status_29_reg_t status_29; // [593:588]
    axi_llc_status_reg2hw_status_30_reg_t status_30; // [587:582]
    axi_llc_status_reg2hw_status_31_reg_t status_31; // [581:576]
    axi_llc_status_reg2hw_status_32_reg_t status_32; // [575:570]
    axi_llc_status_reg2hw_status_33_reg_t status_33; // [569:564]
    axi_llc_status_reg2hw_status_34_reg_t status_34; // [563:558]
    axi_llc_status_reg2hw_status_35_reg_t status_35; // [557:552]
    axi_llc_status_reg2hw_status_36_reg_t status_36; // [551:546]
    axi_llc_status_reg2hw_status_37_reg_t status_37; // [545:540]
    axi_llc_status_reg2hw_status_38_reg_t status_38; // [539:534]
    axi_llc_status_reg2hw_status_39_reg_t status_39; // [533:528]
    axi_llc_status_reg2hw_status_40_reg_t status_40; // [527:522]
    axi_llc_status_reg2hw_status_41_reg_t status_41; // [521:516]
    axi_llc_status_reg2hw_status_42_reg_t status_42; // [515:510]
    axi_llc_status_reg2hw_status_43_reg_t status_43; // [509:504]
    axi_llc_status_reg2hw_status_44_reg_t status_44; // [503:498]
    axi_llc_status_reg2hw_status_45_reg_t status_45; // [497:492]
    axi_llc_status_reg2hw_status_46_reg_t status_46; // [491:486]
    axi_llc_status_reg2hw_status_47_reg_t status_47; // [485:480]
    axi_llc_status_reg2hw_status_48_reg_t status_48; // [479:474]
    axi_llc_status_reg2hw_status_49_reg_t status_49; // [473:468]
    axi_llc_status_reg2hw_status_50_reg_t status_50; // [467:462]
    axi_llc_status_reg2hw_status_51_reg_t status_51; // [461:456]
    axi_llc_status_reg2hw_status_52_reg_t status_52; // [455:450]
    axi_llc_status_reg2hw_status_53_reg_t status_53; // [449:444]
    axi_llc_status_reg2hw_status_54_reg_t status_54; // [443:438]
    axi_llc_status_reg2hw_status_55_reg_t status_55; // [437:432]
    axi_llc_status_reg2hw_status_56_reg_t status_56; // [431:426]
    axi_llc_status_reg2hw_status_57_reg_t status_57; // [425:420]
    axi_llc_status_reg2hw_status_58_reg_t status_58; // [419:414]
    axi_llc_status_reg2hw_status_59_reg_t status_59; // [413:408]
    axi_llc_status_reg2hw_status_60_reg_t status_60; // [407:402]
    axi_llc_status_reg2hw_status_61_reg_t status_61; // [401:396]
    axi_llc_status_reg2hw_status_62_reg_t status_62; // [395:390]
    axi_llc_status_reg2hw_status_63_reg_t status_63; // [389:384]
    axi_llc_status_reg2hw_status_64_reg_t status_64; // [383:378]
    axi_llc_status_reg2hw_status_65_reg_t status_65; // [377:372]
    axi_llc_status_reg2hw_status_66_reg_t status_66; // [371:366]
    axi_llc_status_reg2hw_status_67_reg_t status_67; // [365:360]
    axi_llc_status_reg2hw_status_68_reg_t status_68; // [359:354]
    axi_llc_status_reg2hw_status_69_reg_t status_69; // [353:348]
    axi_llc_status_reg2hw_status_70_reg_t status_70; // [347:342]
    axi_llc_status_reg2hw_status_71_reg_t status_71; // [341:336]
    axi_llc_status_reg2hw_status_72_reg_t status_72; // [335:330]
    axi_llc_status_reg2hw_status_73_reg_t status_73; // [329:324]
    axi_llc_status_reg2hw_status_74_reg_t status_74; // [323:318]
    axi_llc_status_reg2hw_status_75_reg_t status_75; // [317:312]
    axi_llc_status_reg2hw_status_76_reg_t status_76; // [311:306]
    axi_llc_status_reg2hw_status_77_reg_t status_77; // [305:300]
    axi_llc_status_reg2hw_status_78_reg_t status_78; // [299:294]
    axi_llc_status_reg2hw_status_79_reg_t status_79; // [293:288]
    axi_llc_status_reg2hw_status_80_reg_t status_80; // [287:282]
    axi_llc_status_reg2hw_status_81_reg_t status_81; // [281:276]
    axi_llc_status_reg2hw_status_82_reg_t status_82; // [275:270]
    axi_llc_status_reg2hw_status_83_reg_t status_83; // [269:264]
    axi_llc_status_reg2hw_status_84_reg_t status_84; // [263:258]
    axi_llc_status_reg2hw_status_85_reg_t status_85; // [257:252]
    axi_llc_status_reg2hw_status_86_reg_t status_86; // [251:246]
    axi_llc_status_reg2hw_status_87_reg_t status_87; // [245:240]
    axi_llc_status_reg2hw_status_88_reg_t status_88; // [239:234]
    axi_llc_status_reg2hw_status_89_reg_t status_89; // [233:228]
    axi_llc_status_reg2hw_status_90_reg_t status_90; // [227:222]
    axi_llc_status_reg2hw_status_91_reg_t status_91; // [221:216]
    axi_llc_status_reg2hw_status_92_reg_t status_92; // [215:210]
    axi_llc_status_reg2hw_status_93_reg_t status_93; // [209:204]
    axi_llc_status_reg2hw_status_94_reg_t status_94; // [203:198]
    axi_llc_status_reg2hw_status_95_reg_t status_95; // [197:192]
    axi_llc_status_reg2hw_status_96_reg_t status_96; // [191:186]
    axi_llc_status_reg2hw_status_97_reg_t status_97; // [185:180]
    axi_llc_status_reg2hw_status_98_reg_t status_98; // [179:174]
    axi_llc_status_reg2hw_status_99_reg_t status_99; // [173:168]
    axi_llc_status_reg2hw_status_100_reg_t status_100; // [167:162]
    axi_llc_status_reg2hw_status_101_reg_t status_101; // [161:156]
    axi_llc_status_reg2hw_status_102_reg_t status_102; // [155:150]
    axi_llc_status_reg2hw_status_103_reg_t status_103; // [149:144]
    axi_llc_status_reg2hw_status_104_reg_t status_104; // [143:138]
    axi_llc_status_reg2hw_status_105_reg_t status_105; // [137:132]
    axi_llc_status_reg2hw_status_106_reg_t status_106; // [131:126]
    axi_llc_status_reg2hw_status_107_reg_t status_107; // [125:120]
    axi_llc_status_reg2hw_status_108_reg_t status_108; // [119:114]
    axi_llc_status_reg2hw_status_109_reg_t status_109; // [113:108]
    axi_llc_status_reg2hw_status_110_reg_t status_110; // [107:102]
    axi_llc_status_reg2hw_status_111_reg_t status_111; // [101:96]
    axi_llc_status_reg2hw_status_112_reg_t status_112; // [95:90]
    axi_llc_status_reg2hw_status_113_reg_t status_113; // [89:84]
    axi_llc_status_reg2hw_status_114_reg_t status_114; // [83:78]
    axi_llc_status_reg2hw_status_115_reg_t status_115; // [77:72]
    axi_llc_status_reg2hw_status_116_reg_t status_116; // [71:66]
    axi_llc_status_reg2hw_status_117_reg_t status_117; // [65:60]
    axi_llc_status_reg2hw_status_118_reg_t status_118; // [59:54]
    axi_llc_status_reg2hw_status_119_reg_t status_119; // [53:48]
    axi_llc_status_reg2hw_status_120_reg_t status_120; // [47:42]
    axi_llc_status_reg2hw_status_121_reg_t status_121; // [41:36]
    axi_llc_status_reg2hw_status_122_reg_t status_122; // [35:30]
    axi_llc_status_reg2hw_status_123_reg_t status_123; // [29:24]
    axi_llc_status_reg2hw_status_124_reg_t status_124; // [23:18]
    axi_llc_status_reg2hw_status_125_reg_t status_125; // [17:12]
    axi_llc_status_reg2hw_status_126_reg_t status_126; // [11:6]
    axi_llc_status_reg2hw_status_127_reg_t status_127; // [5:0]
  } axi_llc_status_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    axi_llc_status_hw2reg_status_0_reg_t status_0; // [511:508]
    axi_llc_status_hw2reg_status_1_reg_t status_1; // [507:504]
    axi_llc_status_hw2reg_status_2_reg_t status_2; // [503:500]
    axi_llc_status_hw2reg_status_3_reg_t status_3; // [499:496]
    axi_llc_status_hw2reg_status_4_reg_t status_4; // [495:492]
    axi_llc_status_hw2reg_status_5_reg_t status_5; // [491:488]
    axi_llc_status_hw2reg_status_6_reg_t status_6; // [487:484]
    axi_llc_status_hw2reg_status_7_reg_t status_7; // [483:480]
    axi_llc_status_hw2reg_status_8_reg_t status_8; // [479:476]
    axi_llc_status_hw2reg_status_9_reg_t status_9; // [475:472]
    axi_llc_status_hw2reg_status_10_reg_t status_10; // [471:468]
    axi_llc_status_hw2reg_status_11_reg_t status_11; // [467:464]
    axi_llc_status_hw2reg_status_12_reg_t status_12; // [463:460]
    axi_llc_status_hw2reg_status_13_reg_t status_13; // [459:456]
    axi_llc_status_hw2reg_status_14_reg_t status_14; // [455:452]
    axi_llc_status_hw2reg_status_15_reg_t status_15; // [451:448]
    axi_llc_status_hw2reg_status_16_reg_t status_16; // [447:444]
    axi_llc_status_hw2reg_status_17_reg_t status_17; // [443:440]
    axi_llc_status_hw2reg_status_18_reg_t status_18; // [439:436]
    axi_llc_status_hw2reg_status_19_reg_t status_19; // [435:432]
    axi_llc_status_hw2reg_status_20_reg_t status_20; // [431:428]
    axi_llc_status_hw2reg_status_21_reg_t status_21; // [427:424]
    axi_llc_status_hw2reg_status_22_reg_t status_22; // [423:420]
    axi_llc_status_hw2reg_status_23_reg_t status_23; // [419:416]
    axi_llc_status_hw2reg_status_24_reg_t status_24; // [415:412]
    axi_llc_status_hw2reg_status_25_reg_t status_25; // [411:408]
    axi_llc_status_hw2reg_status_26_reg_t status_26; // [407:404]
    axi_llc_status_hw2reg_status_27_reg_t status_27; // [403:400]
    axi_llc_status_hw2reg_status_28_reg_t status_28; // [399:396]
    axi_llc_status_hw2reg_status_29_reg_t status_29; // [395:392]
    axi_llc_status_hw2reg_status_30_reg_t status_30; // [391:388]
    axi_llc_status_hw2reg_status_31_reg_t status_31; // [387:384]
    axi_llc_status_hw2reg_status_32_reg_t status_32; // [383:380]
    axi_llc_status_hw2reg_status_33_reg_t status_33; // [379:376]
    axi_llc_status_hw2reg_status_34_reg_t status_34; // [375:372]
    axi_llc_status_hw2reg_status_35_reg_t status_35; // [371:368]
    axi_llc_status_hw2reg_status_36_reg_t status_36; // [367:364]
    axi_llc_status_hw2reg_status_37_reg_t status_37; // [363:360]
    axi_llc_status_hw2reg_status_38_reg_t status_38; // [359:356]
    axi_llc_status_hw2reg_status_39_reg_t status_39; // [355:352]
    axi_llc_status_hw2reg_status_40_reg_t status_40; // [351:348]
    axi_llc_status_hw2reg_status_41_reg_t status_41; // [347:344]
    axi_llc_status_hw2reg_status_42_reg_t status_42; // [343:340]
    axi_llc_status_hw2reg_status_43_reg_t status_43; // [339:336]
    axi_llc_status_hw2reg_status_44_reg_t status_44; // [335:332]
    axi_llc_status_hw2reg_status_45_reg_t status_45; // [331:328]
    axi_llc_status_hw2reg_status_46_reg_t status_46; // [327:324]
    axi_llc_status_hw2reg_status_47_reg_t status_47; // [323:320]
    axi_llc_status_hw2reg_status_48_reg_t status_48; // [319:316]
    axi_llc_status_hw2reg_status_49_reg_t status_49; // [315:312]
    axi_llc_status_hw2reg_status_50_reg_t status_50; // [311:308]
    axi_llc_status_hw2reg_status_51_reg_t status_51; // [307:304]
    axi_llc_status_hw2reg_status_52_reg_t status_52; // [303:300]
    axi_llc_status_hw2reg_status_53_reg_t status_53; // [299:296]
    axi_llc_status_hw2reg_status_54_reg_t status_54; // [295:292]
    axi_llc_status_hw2reg_status_55_reg_t status_55; // [291:288]
    axi_llc_status_hw2reg_status_56_reg_t status_56; // [287:284]
    axi_llc_status_hw2reg_status_57_reg_t status_57; // [283:280]
    axi_llc_status_hw2reg_status_58_reg_t status_58; // [279:276]
    axi_llc_status_hw2reg_status_59_reg_t status_59; // [275:272]
    axi_llc_status_hw2reg_status_60_reg_t status_60; // [271:268]
    axi_llc_status_hw2reg_status_61_reg_t status_61; // [267:264]
    axi_llc_status_hw2reg_status_62_reg_t status_62; // [263:260]
    axi_llc_status_hw2reg_status_63_reg_t status_63; // [259:256]
    axi_llc_status_hw2reg_status_64_reg_t status_64; // [255:252]
    axi_llc_status_hw2reg_status_65_reg_t status_65; // [251:248]
    axi_llc_status_hw2reg_status_66_reg_t status_66; // [247:244]
    axi_llc_status_hw2reg_status_67_reg_t status_67; // [243:240]
    axi_llc_status_hw2reg_status_68_reg_t status_68; // [239:236]
    axi_llc_status_hw2reg_status_69_reg_t status_69; // [235:232]
    axi_llc_status_hw2reg_status_70_reg_t status_70; // [231:228]
    axi_llc_status_hw2reg_status_71_reg_t status_71; // [227:224]
    axi_llc_status_hw2reg_status_72_reg_t status_72; // [223:220]
    axi_llc_status_hw2reg_status_73_reg_t status_73; // [219:216]
    axi_llc_status_hw2reg_status_74_reg_t status_74; // [215:212]
    axi_llc_status_hw2reg_status_75_reg_t status_75; // [211:208]
    axi_llc_status_hw2reg_status_76_reg_t status_76; // [207:204]
    axi_llc_status_hw2reg_status_77_reg_t status_77; // [203:200]
    axi_llc_status_hw2reg_status_78_reg_t status_78; // [199:196]
    axi_llc_status_hw2reg_status_79_reg_t status_79; // [195:192]
    axi_llc_status_hw2reg_status_80_reg_t status_80; // [191:188]
    axi_llc_status_hw2reg_status_81_reg_t status_81; // [187:184]
    axi_llc_status_hw2reg_status_82_reg_t status_82; // [183:180]
    axi_llc_status_hw2reg_status_83_reg_t status_83; // [179:176]
    axi_llc_status_hw2reg_status_84_reg_t status_84; // [175:172]
    axi_llc_status_hw2reg_status_85_reg_t status_85; // [171:168]
    axi_llc_status_hw2reg_status_86_reg_t status_86; // [167:164]
    axi_llc_status_hw2reg_status_87_reg_t status_87; // [163:160]
    axi_llc_status_hw2reg_status_88_reg_t status_88; // [159:156]
    axi_llc_status_hw2reg_status_89_reg_t status_89; // [155:152]
    axi_llc_status_hw2reg_status_90_reg_t status_90; // [151:148]
    axi_llc_status_hw2reg_status_91_reg_t status_91; // [147:144]
    axi_llc_status_hw2reg_status_92_reg_t status_92; // [143:140]
    axi_llc_status_hw2reg_status_93_reg_t status_93; // [139:136]
    axi_llc_status_hw2reg_status_94_reg_t status_94; // [135:132]
    axi_llc_status_hw2reg_status_95_reg_t status_95; // [131:128]
    axi_llc_status_hw2reg_status_96_reg_t status_96; // [127:124]
    axi_llc_status_hw2reg_status_97_reg_t status_97; // [123:120]
    axi_llc_status_hw2reg_status_98_reg_t status_98; // [119:116]
    axi_llc_status_hw2reg_status_99_reg_t status_99; // [115:112]
    axi_llc_status_hw2reg_status_100_reg_t status_100; // [111:108]
    axi_llc_status_hw2reg_status_101_reg_t status_101; // [107:104]
    axi_llc_status_hw2reg_status_102_reg_t status_102; // [103:100]
    axi_llc_status_hw2reg_status_103_reg_t status_103; // [99:96]
    axi_llc_status_hw2reg_status_104_reg_t status_104; // [95:92]
    axi_llc_status_hw2reg_status_105_reg_t status_105; // [91:88]
    axi_llc_status_hw2reg_status_106_reg_t status_106; // [87:84]
    axi_llc_status_hw2reg_status_107_reg_t status_107; // [83:80]
    axi_llc_status_hw2reg_status_108_reg_t status_108; // [79:76]
    axi_llc_status_hw2reg_status_109_reg_t status_109; // [75:72]
    axi_llc_status_hw2reg_status_110_reg_t status_110; // [71:68]
    axi_llc_status_hw2reg_status_111_reg_t status_111; // [67:64]
    axi_llc_status_hw2reg_status_112_reg_t status_112; // [63:60]
    axi_llc_status_hw2reg_status_113_reg_t status_113; // [59:56]
    axi_llc_status_hw2reg_status_114_reg_t status_114; // [55:52]
    axi_llc_status_hw2reg_status_115_reg_t status_115; // [51:48]
    axi_llc_status_hw2reg_status_116_reg_t status_116; // [47:44]
    axi_llc_status_hw2reg_status_117_reg_t status_117; // [43:40]
    axi_llc_status_hw2reg_status_118_reg_t status_118; // [39:36]
    axi_llc_status_hw2reg_status_119_reg_t status_119; // [35:32]
    axi_llc_status_hw2reg_status_120_reg_t status_120; // [31:28]
    axi_llc_status_hw2reg_status_121_reg_t status_121; // [27:24]
    axi_llc_status_hw2reg_status_122_reg_t status_122; // [23:20]
    axi_llc_status_hw2reg_status_123_reg_t status_123; // [19:16]
    axi_llc_status_hw2reg_status_124_reg_t status_124; // [15:12]
    axi_llc_status_hw2reg_status_125_reg_t status_125; // [11:8]
    axi_llc_status_hw2reg_status_126_reg_t status_126; // [7:4]
    axi_llc_status_hw2reg_status_127_reg_t status_127; // [3:0]
  } axi_llc_status_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_0_OFFSET = 9'h 0;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_1_OFFSET = 9'h 4;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_2_OFFSET = 9'h 8;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_3_OFFSET = 9'h c;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_4_OFFSET = 9'h 10;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_5_OFFSET = 9'h 14;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_6_OFFSET = 9'h 18;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_7_OFFSET = 9'h 1c;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_8_OFFSET = 9'h 20;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_9_OFFSET = 9'h 24;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_10_OFFSET = 9'h 28;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_11_OFFSET = 9'h 2c;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_12_OFFSET = 9'h 30;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_13_OFFSET = 9'h 34;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_14_OFFSET = 9'h 38;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_15_OFFSET = 9'h 3c;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_16_OFFSET = 9'h 40;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_17_OFFSET = 9'h 44;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_18_OFFSET = 9'h 48;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_19_OFFSET = 9'h 4c;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_20_OFFSET = 9'h 50;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_21_OFFSET = 9'h 54;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_22_OFFSET = 9'h 58;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_23_OFFSET = 9'h 5c;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_24_OFFSET = 9'h 60;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_25_OFFSET = 9'h 64;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_26_OFFSET = 9'h 68;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_27_OFFSET = 9'h 6c;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_28_OFFSET = 9'h 70;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_29_OFFSET = 9'h 74;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_30_OFFSET = 9'h 78;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_31_OFFSET = 9'h 7c;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_32_OFFSET = 9'h 80;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_33_OFFSET = 9'h 84;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_34_OFFSET = 9'h 88;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_35_OFFSET = 9'h 8c;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_36_OFFSET = 9'h 90;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_37_OFFSET = 9'h 94;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_38_OFFSET = 9'h 98;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_39_OFFSET = 9'h 9c;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_40_OFFSET = 9'h a0;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_41_OFFSET = 9'h a4;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_42_OFFSET = 9'h a8;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_43_OFFSET = 9'h ac;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_44_OFFSET = 9'h b0;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_45_OFFSET = 9'h b4;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_46_OFFSET = 9'h b8;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_47_OFFSET = 9'h bc;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_48_OFFSET = 9'h c0;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_49_OFFSET = 9'h c4;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_50_OFFSET = 9'h c8;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_51_OFFSET = 9'h cc;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_52_OFFSET = 9'h d0;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_53_OFFSET = 9'h d4;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_54_OFFSET = 9'h d8;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_55_OFFSET = 9'h dc;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_56_OFFSET = 9'h e0;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_57_OFFSET = 9'h e4;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_58_OFFSET = 9'h e8;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_59_OFFSET = 9'h ec;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_60_OFFSET = 9'h f0;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_61_OFFSET = 9'h f4;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_62_OFFSET = 9'h f8;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_63_OFFSET = 9'h fc;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_64_OFFSET = 9'h 100;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_65_OFFSET = 9'h 104;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_66_OFFSET = 9'h 108;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_67_OFFSET = 9'h 10c;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_68_OFFSET = 9'h 110;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_69_OFFSET = 9'h 114;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_70_OFFSET = 9'h 118;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_71_OFFSET = 9'h 11c;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_72_OFFSET = 9'h 120;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_73_OFFSET = 9'h 124;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_74_OFFSET = 9'h 128;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_75_OFFSET = 9'h 12c;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_76_OFFSET = 9'h 130;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_77_OFFSET = 9'h 134;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_78_OFFSET = 9'h 138;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_79_OFFSET = 9'h 13c;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_80_OFFSET = 9'h 140;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_81_OFFSET = 9'h 144;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_82_OFFSET = 9'h 148;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_83_OFFSET = 9'h 14c;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_84_OFFSET = 9'h 150;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_85_OFFSET = 9'h 154;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_86_OFFSET = 9'h 158;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_87_OFFSET = 9'h 15c;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_88_OFFSET = 9'h 160;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_89_OFFSET = 9'h 164;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_90_OFFSET = 9'h 168;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_91_OFFSET = 9'h 16c;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_92_OFFSET = 9'h 170;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_93_OFFSET = 9'h 174;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_94_OFFSET = 9'h 178;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_95_OFFSET = 9'h 17c;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_96_OFFSET = 9'h 180;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_97_OFFSET = 9'h 184;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_98_OFFSET = 9'h 188;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_99_OFFSET = 9'h 18c;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_100_OFFSET = 9'h 190;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_101_OFFSET = 9'h 194;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_102_OFFSET = 9'h 198;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_103_OFFSET = 9'h 19c;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_104_OFFSET = 9'h 1a0;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_105_OFFSET = 9'h 1a4;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_106_OFFSET = 9'h 1a8;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_107_OFFSET = 9'h 1ac;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_108_OFFSET = 9'h 1b0;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_109_OFFSET = 9'h 1b4;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_110_OFFSET = 9'h 1b8;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_111_OFFSET = 9'h 1bc;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_112_OFFSET = 9'h 1c0;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_113_OFFSET = 9'h 1c4;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_114_OFFSET = 9'h 1c8;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_115_OFFSET = 9'h 1cc;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_116_OFFSET = 9'h 1d0;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_117_OFFSET = 9'h 1d4;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_118_OFFSET = 9'h 1d8;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_119_OFFSET = 9'h 1dc;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_120_OFFSET = 9'h 1e0;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_121_OFFSET = 9'h 1e4;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_122_OFFSET = 9'h 1e8;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_123_OFFSET = 9'h 1ec;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_124_OFFSET = 9'h 1f0;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_125_OFFSET = 9'h 1f4;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_126_OFFSET = 9'h 1f8;
  parameter logic [BlockAw-1:0] AXI_LLC_STATUS_STATUS_127_OFFSET = 9'h 1fc;

  // Reset values for hwext registers and their fields
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_0_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_1_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_2_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_3_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_4_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_5_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_6_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_7_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_8_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_9_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_10_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_11_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_12_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_13_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_14_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_15_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_16_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_17_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_18_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_19_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_20_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_21_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_22_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_23_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_24_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_25_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_26_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_27_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_28_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_29_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_30_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_31_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_32_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_33_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_34_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_35_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_36_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_37_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_38_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_39_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_40_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_41_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_42_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_43_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_44_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_45_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_46_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_47_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_48_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_49_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_50_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_51_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_52_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_53_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_54_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_55_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_56_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_57_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_58_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_59_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_60_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_61_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_62_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_63_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_64_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_65_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_66_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_67_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_68_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_69_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_70_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_71_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_72_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_73_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_74_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_75_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_76_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_77_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_78_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_79_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_80_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_81_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_82_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_83_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_84_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_85_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_86_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_87_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_88_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_89_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_90_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_91_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_92_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_93_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_94_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_95_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_96_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_97_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_98_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_99_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_100_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_101_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_102_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_103_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_104_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_105_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_106_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_107_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_108_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_109_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_110_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_111_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_112_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_113_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_114_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_115_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_116_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_117_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_118_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_119_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_120_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_121_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_122_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_123_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_124_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_125_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_126_RESVAL = 20'h 0;
  parameter logic [19:0] AXI_LLC_STATUS_STATUS_127_RESVAL = 20'h 0;

  // Register index
  typedef enum int {
    AXI_LLC_STATUS_STATUS_0,
    AXI_LLC_STATUS_STATUS_1,
    AXI_LLC_STATUS_STATUS_2,
    AXI_LLC_STATUS_STATUS_3,
    AXI_LLC_STATUS_STATUS_4,
    AXI_LLC_STATUS_STATUS_5,
    AXI_LLC_STATUS_STATUS_6,
    AXI_LLC_STATUS_STATUS_7,
    AXI_LLC_STATUS_STATUS_8,
    AXI_LLC_STATUS_STATUS_9,
    AXI_LLC_STATUS_STATUS_10,
    AXI_LLC_STATUS_STATUS_11,
    AXI_LLC_STATUS_STATUS_12,
    AXI_LLC_STATUS_STATUS_13,
    AXI_LLC_STATUS_STATUS_14,
    AXI_LLC_STATUS_STATUS_15,
    AXI_LLC_STATUS_STATUS_16,
    AXI_LLC_STATUS_STATUS_17,
    AXI_LLC_STATUS_STATUS_18,
    AXI_LLC_STATUS_STATUS_19,
    AXI_LLC_STATUS_STATUS_20,
    AXI_LLC_STATUS_STATUS_21,
    AXI_LLC_STATUS_STATUS_22,
    AXI_LLC_STATUS_STATUS_23,
    AXI_LLC_STATUS_STATUS_24,
    AXI_LLC_STATUS_STATUS_25,
    AXI_LLC_STATUS_STATUS_26,
    AXI_LLC_STATUS_STATUS_27,
    AXI_LLC_STATUS_STATUS_28,
    AXI_LLC_STATUS_STATUS_29,
    AXI_LLC_STATUS_STATUS_30,
    AXI_LLC_STATUS_STATUS_31,
    AXI_LLC_STATUS_STATUS_32,
    AXI_LLC_STATUS_STATUS_33,
    AXI_LLC_STATUS_STATUS_34,
    AXI_LLC_STATUS_STATUS_35,
    AXI_LLC_STATUS_STATUS_36,
    AXI_LLC_STATUS_STATUS_37,
    AXI_LLC_STATUS_STATUS_38,
    AXI_LLC_STATUS_STATUS_39,
    AXI_LLC_STATUS_STATUS_40,
    AXI_LLC_STATUS_STATUS_41,
    AXI_LLC_STATUS_STATUS_42,
    AXI_LLC_STATUS_STATUS_43,
    AXI_LLC_STATUS_STATUS_44,
    AXI_LLC_STATUS_STATUS_45,
    AXI_LLC_STATUS_STATUS_46,
    AXI_LLC_STATUS_STATUS_47,
    AXI_LLC_STATUS_STATUS_48,
    AXI_LLC_STATUS_STATUS_49,
    AXI_LLC_STATUS_STATUS_50,
    AXI_LLC_STATUS_STATUS_51,
    AXI_LLC_STATUS_STATUS_52,
    AXI_LLC_STATUS_STATUS_53,
    AXI_LLC_STATUS_STATUS_54,
    AXI_LLC_STATUS_STATUS_55,
    AXI_LLC_STATUS_STATUS_56,
    AXI_LLC_STATUS_STATUS_57,
    AXI_LLC_STATUS_STATUS_58,
    AXI_LLC_STATUS_STATUS_59,
    AXI_LLC_STATUS_STATUS_60,
    AXI_LLC_STATUS_STATUS_61,
    AXI_LLC_STATUS_STATUS_62,
    AXI_LLC_STATUS_STATUS_63,
    AXI_LLC_STATUS_STATUS_64,
    AXI_LLC_STATUS_STATUS_65,
    AXI_LLC_STATUS_STATUS_66,
    AXI_LLC_STATUS_STATUS_67,
    AXI_LLC_STATUS_STATUS_68,
    AXI_LLC_STATUS_STATUS_69,
    AXI_LLC_STATUS_STATUS_70,
    AXI_LLC_STATUS_STATUS_71,
    AXI_LLC_STATUS_STATUS_72,
    AXI_LLC_STATUS_STATUS_73,
    AXI_LLC_STATUS_STATUS_74,
    AXI_LLC_STATUS_STATUS_75,
    AXI_LLC_STATUS_STATUS_76,
    AXI_LLC_STATUS_STATUS_77,
    AXI_LLC_STATUS_STATUS_78,
    AXI_LLC_STATUS_STATUS_79,
    AXI_LLC_STATUS_STATUS_80,
    AXI_LLC_STATUS_STATUS_81,
    AXI_LLC_STATUS_STATUS_82,
    AXI_LLC_STATUS_STATUS_83,
    AXI_LLC_STATUS_STATUS_84,
    AXI_LLC_STATUS_STATUS_85,
    AXI_LLC_STATUS_STATUS_86,
    AXI_LLC_STATUS_STATUS_87,
    AXI_LLC_STATUS_STATUS_88,
    AXI_LLC_STATUS_STATUS_89,
    AXI_LLC_STATUS_STATUS_90,
    AXI_LLC_STATUS_STATUS_91,
    AXI_LLC_STATUS_STATUS_92,
    AXI_LLC_STATUS_STATUS_93,
    AXI_LLC_STATUS_STATUS_94,
    AXI_LLC_STATUS_STATUS_95,
    AXI_LLC_STATUS_STATUS_96,
    AXI_LLC_STATUS_STATUS_97,
    AXI_LLC_STATUS_STATUS_98,
    AXI_LLC_STATUS_STATUS_99,
    AXI_LLC_STATUS_STATUS_100,
    AXI_LLC_STATUS_STATUS_101,
    AXI_LLC_STATUS_STATUS_102,
    AXI_LLC_STATUS_STATUS_103,
    AXI_LLC_STATUS_STATUS_104,
    AXI_LLC_STATUS_STATUS_105,
    AXI_LLC_STATUS_STATUS_106,
    AXI_LLC_STATUS_STATUS_107,
    AXI_LLC_STATUS_STATUS_108,
    AXI_LLC_STATUS_STATUS_109,
    AXI_LLC_STATUS_STATUS_110,
    AXI_LLC_STATUS_STATUS_111,
    AXI_LLC_STATUS_STATUS_112,
    AXI_LLC_STATUS_STATUS_113,
    AXI_LLC_STATUS_STATUS_114,
    AXI_LLC_STATUS_STATUS_115,
    AXI_LLC_STATUS_STATUS_116,
    AXI_LLC_STATUS_STATUS_117,
    AXI_LLC_STATUS_STATUS_118,
    AXI_LLC_STATUS_STATUS_119,
    AXI_LLC_STATUS_STATUS_120,
    AXI_LLC_STATUS_STATUS_121,
    AXI_LLC_STATUS_STATUS_122,
    AXI_LLC_STATUS_STATUS_123,
    AXI_LLC_STATUS_STATUS_124,
    AXI_LLC_STATUS_STATUS_125,
    AXI_LLC_STATUS_STATUS_126,
    AXI_LLC_STATUS_STATUS_127
  } axi_llc_status_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] AXI_LLC_STATUS_PERMIT [128] = '{
    4'b 0111, // index[  0] AXI_LLC_STATUS_STATUS_0
    4'b 0111, // index[  1] AXI_LLC_STATUS_STATUS_1
    4'b 0111, // index[  2] AXI_LLC_STATUS_STATUS_2
    4'b 0111, // index[  3] AXI_LLC_STATUS_STATUS_3
    4'b 0111, // index[  4] AXI_LLC_STATUS_STATUS_4
    4'b 0111, // index[  5] AXI_LLC_STATUS_STATUS_5
    4'b 0111, // index[  6] AXI_LLC_STATUS_STATUS_6
    4'b 0111, // index[  7] AXI_LLC_STATUS_STATUS_7
    4'b 0111, // index[  8] AXI_LLC_STATUS_STATUS_8
    4'b 0111, // index[  9] AXI_LLC_STATUS_STATUS_9
    4'b 0111, // index[ 10] AXI_LLC_STATUS_STATUS_10
    4'b 0111, // index[ 11] AXI_LLC_STATUS_STATUS_11
    4'b 0111, // index[ 12] AXI_LLC_STATUS_STATUS_12
    4'b 0111, // index[ 13] AXI_LLC_STATUS_STATUS_13
    4'b 0111, // index[ 14] AXI_LLC_STATUS_STATUS_14
    4'b 0111, // index[ 15] AXI_LLC_STATUS_STATUS_15
    4'b 0111, // index[ 16] AXI_LLC_STATUS_STATUS_16
    4'b 0111, // index[ 17] AXI_LLC_STATUS_STATUS_17
    4'b 0111, // index[ 18] AXI_LLC_STATUS_STATUS_18
    4'b 0111, // index[ 19] AXI_LLC_STATUS_STATUS_19
    4'b 0111, // index[ 20] AXI_LLC_STATUS_STATUS_20
    4'b 0111, // index[ 21] AXI_LLC_STATUS_STATUS_21
    4'b 0111, // index[ 22] AXI_LLC_STATUS_STATUS_22
    4'b 0111, // index[ 23] AXI_LLC_STATUS_STATUS_23
    4'b 0111, // index[ 24] AXI_LLC_STATUS_STATUS_24
    4'b 0111, // index[ 25] AXI_LLC_STATUS_STATUS_25
    4'b 0111, // index[ 26] AXI_LLC_STATUS_STATUS_26
    4'b 0111, // index[ 27] AXI_LLC_STATUS_STATUS_27
    4'b 0111, // index[ 28] AXI_LLC_STATUS_STATUS_28
    4'b 0111, // index[ 29] AXI_LLC_STATUS_STATUS_29
    4'b 0111, // index[ 30] AXI_LLC_STATUS_STATUS_30
    4'b 0111, // index[ 31] AXI_LLC_STATUS_STATUS_31
    4'b 0111, // index[ 32] AXI_LLC_STATUS_STATUS_32
    4'b 0111, // index[ 33] AXI_LLC_STATUS_STATUS_33
    4'b 0111, // index[ 34] AXI_LLC_STATUS_STATUS_34
    4'b 0111, // index[ 35] AXI_LLC_STATUS_STATUS_35
    4'b 0111, // index[ 36] AXI_LLC_STATUS_STATUS_36
    4'b 0111, // index[ 37] AXI_LLC_STATUS_STATUS_37
    4'b 0111, // index[ 38] AXI_LLC_STATUS_STATUS_38
    4'b 0111, // index[ 39] AXI_LLC_STATUS_STATUS_39
    4'b 0111, // index[ 40] AXI_LLC_STATUS_STATUS_40
    4'b 0111, // index[ 41] AXI_LLC_STATUS_STATUS_41
    4'b 0111, // index[ 42] AXI_LLC_STATUS_STATUS_42
    4'b 0111, // index[ 43] AXI_LLC_STATUS_STATUS_43
    4'b 0111, // index[ 44] AXI_LLC_STATUS_STATUS_44
    4'b 0111, // index[ 45] AXI_LLC_STATUS_STATUS_45
    4'b 0111, // index[ 46] AXI_LLC_STATUS_STATUS_46
    4'b 0111, // index[ 47] AXI_LLC_STATUS_STATUS_47
    4'b 0111, // index[ 48] AXI_LLC_STATUS_STATUS_48
    4'b 0111, // index[ 49] AXI_LLC_STATUS_STATUS_49
    4'b 0111, // index[ 50] AXI_LLC_STATUS_STATUS_50
    4'b 0111, // index[ 51] AXI_LLC_STATUS_STATUS_51
    4'b 0111, // index[ 52] AXI_LLC_STATUS_STATUS_52
    4'b 0111, // index[ 53] AXI_LLC_STATUS_STATUS_53
    4'b 0111, // index[ 54] AXI_LLC_STATUS_STATUS_54
    4'b 0111, // index[ 55] AXI_LLC_STATUS_STATUS_55
    4'b 0111, // index[ 56] AXI_LLC_STATUS_STATUS_56
    4'b 0111, // index[ 57] AXI_LLC_STATUS_STATUS_57
    4'b 0111, // index[ 58] AXI_LLC_STATUS_STATUS_58
    4'b 0111, // index[ 59] AXI_LLC_STATUS_STATUS_59
    4'b 0111, // index[ 60] AXI_LLC_STATUS_STATUS_60
    4'b 0111, // index[ 61] AXI_LLC_STATUS_STATUS_61
    4'b 0111, // index[ 62] AXI_LLC_STATUS_STATUS_62
    4'b 0111, // index[ 63] AXI_LLC_STATUS_STATUS_63
    4'b 0111, // index[ 64] AXI_LLC_STATUS_STATUS_64
    4'b 0111, // index[ 65] AXI_LLC_STATUS_STATUS_65
    4'b 0111, // index[ 66] AXI_LLC_STATUS_STATUS_66
    4'b 0111, // index[ 67] AXI_LLC_STATUS_STATUS_67
    4'b 0111, // index[ 68] AXI_LLC_STATUS_STATUS_68
    4'b 0111, // index[ 69] AXI_LLC_STATUS_STATUS_69
    4'b 0111, // index[ 70] AXI_LLC_STATUS_STATUS_70
    4'b 0111, // index[ 71] AXI_LLC_STATUS_STATUS_71
    4'b 0111, // index[ 72] AXI_LLC_STATUS_STATUS_72
    4'b 0111, // index[ 73] AXI_LLC_STATUS_STATUS_73
    4'b 0111, // index[ 74] AXI_LLC_STATUS_STATUS_74
    4'b 0111, // index[ 75] AXI_LLC_STATUS_STATUS_75
    4'b 0111, // index[ 76] AXI_LLC_STATUS_STATUS_76
    4'b 0111, // index[ 77] AXI_LLC_STATUS_STATUS_77
    4'b 0111, // index[ 78] AXI_LLC_STATUS_STATUS_78
    4'b 0111, // index[ 79] AXI_LLC_STATUS_STATUS_79
    4'b 0111, // index[ 80] AXI_LLC_STATUS_STATUS_80
    4'b 0111, // index[ 81] AXI_LLC_STATUS_STATUS_81
    4'b 0111, // index[ 82] AXI_LLC_STATUS_STATUS_82
    4'b 0111, // index[ 83] AXI_LLC_STATUS_STATUS_83
    4'b 0111, // index[ 84] AXI_LLC_STATUS_STATUS_84
    4'b 0111, // index[ 85] AXI_LLC_STATUS_STATUS_85
    4'b 0111, // index[ 86] AXI_LLC_STATUS_STATUS_86
    4'b 0111, // index[ 87] AXI_LLC_STATUS_STATUS_87
    4'b 0111, // index[ 88] AXI_LLC_STATUS_STATUS_88
    4'b 0111, // index[ 89] AXI_LLC_STATUS_STATUS_89
    4'b 0111, // index[ 90] AXI_LLC_STATUS_STATUS_90
    4'b 0111, // index[ 91] AXI_LLC_STATUS_STATUS_91
    4'b 0111, // index[ 92] AXI_LLC_STATUS_STATUS_92
    4'b 0111, // index[ 93] AXI_LLC_STATUS_STATUS_93
    4'b 0111, // index[ 94] AXI_LLC_STATUS_STATUS_94
    4'b 0111, // index[ 95] AXI_LLC_STATUS_STATUS_95
    4'b 0111, // index[ 96] AXI_LLC_STATUS_STATUS_96
    4'b 0111, // index[ 97] AXI_LLC_STATUS_STATUS_97
    4'b 0111, // index[ 98] AXI_LLC_STATUS_STATUS_98
    4'b 0111, // index[ 99] AXI_LLC_STATUS_STATUS_99
    4'b 0111, // index[100] AXI_LLC_STATUS_STATUS_100
    4'b 0111, // index[101] AXI_LLC_STATUS_STATUS_101
    4'b 0111, // index[102] AXI_LLC_STATUS_STATUS_102
    4'b 0111, // index[103] AXI_LLC_STATUS_STATUS_103
    4'b 0111, // index[104] AXI_LLC_STATUS_STATUS_104
    4'b 0111, // index[105] AXI_LLC_STATUS_STATUS_105
    4'b 0111, // index[106] AXI_LLC_STATUS_STATUS_106
    4'b 0111, // index[107] AXI_LLC_STATUS_STATUS_107
    4'b 0111, // index[108] AXI_LLC_STATUS_STATUS_108
    4'b 0111, // index[109] AXI_LLC_STATUS_STATUS_109
    4'b 0111, // index[110] AXI_LLC_STATUS_STATUS_110
    4'b 0111, // index[111] AXI_LLC_STATUS_STATUS_111
    4'b 0111, // index[112] AXI_LLC_STATUS_STATUS_112
    4'b 0111, // index[113] AXI_LLC_STATUS_STATUS_113
    4'b 0111, // index[114] AXI_LLC_STATUS_STATUS_114
    4'b 0111, // index[115] AXI_LLC_STATUS_STATUS_115
    4'b 0111, // index[116] AXI_LLC_STATUS_STATUS_116
    4'b 0111, // index[117] AXI_LLC_STATUS_STATUS_117
    4'b 0111, // index[118] AXI_LLC_STATUS_STATUS_118
    4'b 0111, // index[119] AXI_LLC_STATUS_STATUS_119
    4'b 0111, // index[120] AXI_LLC_STATUS_STATUS_120
    4'b 0111, // index[121] AXI_LLC_STATUS_STATUS_121
    4'b 0111, // index[122] AXI_LLC_STATUS_STATUS_122
    4'b 0111, // index[123] AXI_LLC_STATUS_STATUS_123
    4'b 0111, // index[124] AXI_LLC_STATUS_STATUS_124
    4'b 0111, // index[125] AXI_LLC_STATUS_STATUS_125
    4'b 0111, // index[126] AXI_LLC_STATUS_STATUS_126
    4'b 0111  // index[127] AXI_LLC_STATUS_STATUS_127
  };

endpackage

